### ISSUE TITLE
Additions to the database

### ISSUE THREAD

**Issue by chartgerink** [jtleek/papr#10]
Hi,

First off, I love `papr`! As I mentioned on Twitter, I had a random thought along these lines a few weeks ago, but I always love to see other people have the same idea but better :100: 

Second, when I started using it I noticed it was rather difficult for me as a social scientist (read: I don't understand most of the preprints). So I wondered what I could do about that. Then I started fiddling around with the Open Science Framework API to download the metadata of their preprint services (PsyArxiv, LawArxiv, SocArxiv, and a few more I think; ~2500 preprints). Trial run: success :godmode: 

Now, I was wondering what would be necessary for a database extension PR to be merged into the current database? [An example](https://github.com/chartgerink/papr/blob/master/collected-osf.csv) of how I collect data now is based on the .Rda file (`dat` object) in the repo. I figured that it would be readily ingestable into your database, but thought I'd open an issue to see if that was the case.

I see much potential for `papr` and really excited to contribute. I think many researchers would love to move the Tinder meat market into the research paper area, _and_ get specific recommendations for them (and get hooked up with researchers with similar interests). :robot: 

Cheers,
Chris

**Comment by LucyMcGowan** [comment]
@chartgerink we've moved the repository -- I've copied your issue over [here](https://github.com/jhudsl/papr/issues/2). Thanks!
